# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.*
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
      - name: Put MSYS2_MinGW64 on PATH
        run: echo "D:/a/_temp/msys64/mingw64/bin" >> $GITHUB_PATH
      - name: generate makefiles
        run: qmake -spec win32-g++ phoenix.pro
      - name: run make
        run: make release
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/